# Generated by Django 2.0 on 2019-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to', models.CharField(max_length=20)),
                ('degree_name', models.CharField(max_length=50)),
                ('degree_title', models.CharField(max_length=50)),
                ('instituation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_name', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=30)),
                ('review_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExprience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=200)),
            ],
        ),
    ]
