# Generated by Django 2.0 on 2019-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='about_degree',
            field=models.CharField(default='abc', max_length=300),
            preserve_default=False,
        ),
    ]
