# Generated by Django 2.0 on 2019-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190912_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='title',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
