# Generated by Django 2.0 on 2019-09-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_basicinfo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='cover_pic',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='profile_pic',
        ),
    ]
